# Generated by Django 3.2.2 on 2021-05-30 21:54

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='photo',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=''),
        ),
    ]
