# Generated by Django 3.1.7 on 2021-06-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuri', '0008_alter_miembro_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='institucion',
            field=models.IntegerField(choices=[[0, 'Hogar de cristo'], [1, 'Cuaniquen'], [2, 'Fundacion las rosas'], [3, 'Fundacion luz'], [4, 'Teleton']], null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='pin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='organizaciones',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organizaciones',
            name='id_organizacion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
