# Generated by Django 3.1.7 on 2021-06-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuri', '0011_auto_20210615_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='institucion',
            field=models.IntegerField(choices=[[1, 'Teletón'], [2, 'Colunga'], [3, 'elpepe'], [4, 'Juan de dios']], null=True, verbose_name='Institución'),
        ),
    ]
