# Generated by Django 3.2.2 on 2021-05-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuri', '0002_miembro_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='photo',
            field=models.ImageField(null=True, upload_to='perfil'),
        ),
    ]
