# Generated by Django 3.2.2 on 2021-06-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuri', '0005_alter_miembro_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='pin',
            field=models.IntegerField(default=0, max_length=15),
        ),
    ]
