# Generated by Django 3.2.2 on 2021-06-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuri', '0006_miembro_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_organizacion', models.CharField(max_length=30)),
                ('email_organizacion', models.EmailField(max_length=254)),
                ('id_organizacion', models.IntegerField(max_length=10)),
                ('descripcion_organizacion', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='miembro',
            name='institucion',
            field=models.CharField(choices=[[0, 'Test'], [1, 'Test2']], max_length=15, null=True),
        ),
    ]
