# Generated by Django 3.2.2 on 2021-06-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuri', '0007_auto_20210602_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='institucion',
            field=models.IntegerField(choices=[[0, 'Test'], [1, 'Test2']], max_length=15, null=True),
        ),
    ]
