# Generated by Django 3.1.7 on 2021-06-16 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuri', '0009_auto_20210604_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizaciones',
            name='id_organizacion',
        ),
        migrations.AlterField(
            model_name='miembro',
            name='apellido_mat',
            field=models.CharField(max_length=15, null=True, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='apellido_pat',
            field=models.CharField(max_length=15, null=True, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='cel',
            field=models.CharField(max_length=15, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='institucion',
            field=models.IntegerField(choices=[(1, 'Teletón'), (2, 'Colunga')], null=True, verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='photo',
            field=models.ImageField(null=True, upload_to='perfil', verbose_name='Foto de perfil'),
        ),
    ]
