# Generated by Django 3.1.7 on 2021-06-16 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apuri', '0010_auto_20210615_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='institucion',
            field=models.ForeignKey(choices=[[1, 'Teletón'], [2, 'Colunga'], [3, 'elpepe'], [4, 'Juan de dios']], null=True, on_delete=django.db.models.deletion.CASCADE, to='apuri.organizaciones', verbose_name='Institución'),
        ),
    ]
