# Generated by Django 3.1.7 on 2021-06-17 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apuri', '0013_auto_20210616_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizaciones',
            name='logo',
            field=models.ImageField(null=True, upload_to='Logos', verbose_name='Logo institución'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='institucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apuri.organizaciones', verbose_name='Institución'),
        ),
    ]
