# Generated by Django 3.1.7 on 2021-06-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuri', '0014_auto_20210616_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizaciones',
            name='email_organizacion',
        ),
        migrations.AddField(
            model_name='organizaciones',
            name='pag_web',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
