# Generated by Django 3.1.7 on 2021-06-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuri', '0015_auto_20210616_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='rol',
            field=models.CharField(choices=[(0, 'Usuario'), (1, 'Administrador')], default='Usuario', max_length=40, verbose_name='Rol'),
        ),
    ]
