# Generated by Django 3.1.7 on 2021-06-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuri', '0017_auto_20210622_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='cargo',
            field=models.CharField(max_length=30, null=True, verbose_name='Cargo'),
        ),
    ]
