# Generated by Django 3.1.7 on 2021-06-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuri', '0018_miembro_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='apellido_mat',
            field=models.CharField(max_length=20, null=True, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='apellido_pat',
            field=models.CharField(max_length=20, null=True, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='contraseña',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='organizaciones',
            name='descripcion_organizacion',
            field=models.TextField(null=True),
        ),
    ]
