# Generated by Django 3.1.7 on 2021-07-03 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apuri', '0020_auto_20210703_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='organ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apuri.organizaciones', verbose_name='Organización'),
        ),
    ]
