# Generated by Django 3.1.7 on 2021-07-04 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apuri', '0021_anuncio_organ'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizaciones',
            name='calendario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='hfin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Termino evento'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='hini',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio evento'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='organ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apuri.organizaciones', verbose_name='Organización'),
        ),
    ]
