# Generated by Django 3.1.7 on 2021-07-05 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apuri', '0022_auto_20210704_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='temas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tema', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tema_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apuri.temas'),
        ),
    ]
