# Generated by Django 3.1.7 on 2021-07-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuri', '0023_auto_20210705_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Anuncios', verbose_name='Foto de Anuncio'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='cargo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='cel',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='organizaciones',
            name='descripcion_organizacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizaciones',
            name='pag_web',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='temas',
            name='nombre_tema',
            field=models.CharField(max_length=200, verbose_name='Tema'),
        ),
    ]
