# Generated by Django 3.1.7 on 2021-07-07 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apuri', '0025_auto_20210706_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='contraseña',
            field=models.CharField(max_length=20, null=True, verbose_name='Contraseña(mín 8)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apuri.miembro'),
        ),
    ]
