# Generated by Django 3.1.7 on 2021-07-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuri', '0026_auto_20210707_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='perfil', verbose_name='Foto de perfil'),
        ),
    ]
