# Generated by Django 3.1.7 on 2021-07-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuri', '0027_auto_20210707_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='photo',
            field=models.ImageField(blank=True, default='perfil/usuario.png', null=True, upload_to='perfil', verbose_name='Foto de perfil'),
        ),
    ]
