# Generated by Django 3.1.7 on 2021-07-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuri', '0028_auto_20210707_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizaciones',
            name='especial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='hfin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Termino evento dd/mm/aa hh:mm:ss '),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='hini',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio evento dd/mm/aa hh:mm:ss '),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='perfil', verbose_name='Foto de perfil'),
        ),
    ]
