# Generated by Django 3.1.7 on 2021-07-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuri', '0029_auto_20210708_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tema_post',
            new_name='tema',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='texto',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titulo',
        ),
        migrations.AlterField(
            model_name='organizaciones',
            name='calendario',
            field=models.TextField(blank=True, null=True, verbose_name='Calendario google'),
        ),
        migrations.AlterField(
            model_name='organizaciones',
            name='descripcion_organizacion',
            field=models.TextField(blank=True, null=True, verbose_name='descrpción'),
        ),
        migrations.AlterField(
            model_name='organizaciones',
            name='especial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='organizaciones',
            name='logo',
            field=models.ImageField(null=True, upload_to='Logos', verbose_name='Logo fundación'),
        ),
        migrations.AlterField(
            model_name='organizaciones',
            name='nombre_organizacion',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='organizaciones',
            name='pag_web',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Página Web'),
        ),
    ]
